#!/system/bin/sh
# My Charging Controller
# mcc Boot S (201807261)
# JayminSuthar @ xda-developers

# Copyright (c) 2018 Jaymin Suthar. All rights reserved.

# This file is a part of "My Charging Controller (mcc)".

# mcc is released under the terms of the GNU GPL v3, as been
## published by the Free Software Foundation. And permission
## hereby is granted to use, modify or redistribute it maybe
## partially or entirely under GPLv3 only.

# mcc was written in a hope of being useful. And any kind of
## warranty is not provided. See GPLv3 for details.

# You should already have received a copy of GPLv3 with mcc,
## if not, see <http://www.gnu.org/licenses/>.

mcc_dir=/data/adb/mcc;
log_dir=$mcc_dir/log;
bin_dir=$mcc_dir/bin;

if [ "$1" == --skip-errors ]; then

  set -x 2>$log_dir/boot.log;

  if [ -f /system_root/system/build.prop ]; then
    system=/system_root/system;
  elif [ -f /system/system/build.prop ]; then
    system=/system/system;
  elif [ -f /system/build.prop ]; then
    system=/system;
  fi;
  main_path=$system/bin/mcc;

  umask 022;
  chmod 0600 $main_path;
  rm $mcc_dir/lock;
  $bin_dir/busybox --install $bin_dir/;
  $bin_dir/sed -i 's/^switch_do=.*/switch_do=default/' $mcc_dir/mcc.conf;

  sleep 120;

  chmod 0755 $main_path;
  disable_mcc_logs=true mcc --launch-daemon </dev/null >/dev/null 2>&1;
  ps | grep -v grep | grep '{mcc}' | grep '\-\-launch\-daemon$' >&2;
else
  $0 --skip-errors 2>$log_dir/boot_err.log;
fi;
